version: '2'
services:
  php:
    volumes:
      - "${compose_dir}/docker_lamp/docker/php/conf/conf:/usr/src/php/conf/"
      - "${compose_dir}/docker_lamp/docker/php/conf/etc/:/usr/src/php/etc/"
    volumes_from: 
      - base
    extends:
      file: "docker-compose-full.yml"
      service: "php"
    networks:
      all:
        aliases: 
          - php

  nginx:
    volumes:
      - "${compose_dir}/docker_lamp/docker/nginx/conf/:/usr/src/nginx/conf/"
    volumes_from: 
      - base
    extends:
      file: "docker-compose-full.yml"
      service: "nginx"

  base:
    volumes:
      - "${compose_volumes_base}"
    extends:
      file: "docker-compose-full.yml"
      service: "base"

networks:
  all: